### ISSUE TITLE
Suppréssion impossible d'un format audio

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary-details#3]
Lorsque l'on sélectionne un format audio et que l'on souhaite le supprimer, il ne s'efface pas.
On a beau cliquer sur la croix, ce qui le supprime bien en apparence, mais lors de l'enregistrement de la fiche et que l'on retourne dans détail, il est encore présent.

**Comment by caercam** [comment]
Vu. Ce n'est pas lié spécifiquement à ce plugin, ça vient du plugin principal. Je ferme ici, corrigé par https://github.com/wpmovielibrary/wpmovielibrary/commit/b7a9aeb53d4bdba7b262b2800eb0de25db6c7cb0.
