### ISSUE TITLE
Séparation du plugin

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary-details#4]
Bonsoir Charlie,
J'ai voulu séparer le plugin en plusieurs plugin pour les détails.
Mais je me retrouve avec un dilemme, j'arrive à faire fonctionner l'un mais pas l'autre en même temps.
Peux tu me dire ce qui ne va pas.
Adresse des plugins : [ICI](https://github.com/lesurfeur/WordPress/tree/master/Plugin)

**Comment by caercam** [comment]
Tu a bien renommé certains fichiers, variables et constantes, mais pas les méthodes et les classes : dans chaque `wpmoly-details-*.php` à la fin du fichier, remplace `class_exists( 'WPMovieLibrary_Details' )` par `class_exists( 'WPMovieLibrary_Details_{type_du_plugin}' )` et `new WPMovieLibrary_Details()` par `new WPMovieLibrary_Details_{type_du_plugin}()`, par exemple `class_exists( 'WPMovieLibrary_Details_Audio' )` et `new WPMovieLibrary_Details_Audio()`. De même pour le début de chaque fichier `class-wpmoly-details-*.php`. Et toujours dans `wpmoly-details-*.php`, remplace `$GLOBALS['wpmoly_details']` par `$GLOBALS['wpmoly_details_{type_du_plugin}']`, par exemple `$GLOBALS['wpmoly_details_audio']`.

Sans cela, les deux ou trois plugins ayant en fait le même nom de classe/variable globale, c'est le dernier chargé qui écrase les autres.

**Comment by lesurfeur** [comment]
Impec, un grand merci.
